### ISSUE TITLE
Documentation Preview

### ISSUE THREAD

**Issue by kevinkhill** [kevinkhill/lavacharts-site#1]
@SendDerek, @marcusirgens, @kyranb, @TheTechnoMan, @emilv, @MicahKV

Hello all, since you have all actively participated with the development of Lavacharts, I was hoping you could check out the new documentation site for 3.0 and give me feedback before it goes live.

[New 3.0 Documentation Site](http://lavadocs.khilldesigns.com/)

Anything you find, just open a new issue in this repo, or comment here.

Thanks!

**Comment by SendDerek** [comment]
I had every intention of helping out with this before it went live, but then got buried in my inbox and forgotten until now.  I suppose the only thing from me would be to include the newly supported "isStacked: percent" or "isStacked: relative" for stacked area charts.  Not sure I had seen anything making reference to that in the documentation, but maybe you assume folks would be reading the Google Charts API documentation at that level.

Congrats again on the release.  I'm upgrading now, getting ready to push to production hopefully. :+1:

**Comment by kevinkhill** [comment]
I'm actually gutting aaaall of the option checking, config objects, and traits from the charts. Just pass an array with whatever options you want and they will be applied, or ignored by Google if invalid.

It makes my life much easier, so much so that I added 6 more charts in one day. Just a few class constants and it works. I also started a DataFactory to make creating DataTables easier.

My only thought is, make it 3.0.1 or 3.1.0

**Comment by SendDerek** [comment]
Sounds good to me!

I remember in my previous job, we had access to an API definition file and used it to dynamically generate code using a lot of reflection and what-not.  This way, when there was an update to the API, our code automatically supported it.  Of course, this was done with a team of developers, not just one guy with a few contributors. :-)

**Comment by kevinkhill** [comment]
If you want to glance at it, I made my private git public

https://git.khilldesigns.com/kevin/lavacharts

**Comment by kevinkhill** [comment]
Check out the simplification branch. If you navigate to the "tests/Examples" dir and run `php -S 127.0.0.1:8000 -c php.ini router.php` to view some examples
