### ISSUE TITLE
Why isn't the Combo chart in the website?

### ISSUE THREAD

**Issue by elpiel** [kevinkhill/lavacharts-site#3]
Both the  [Combo example](https://github.com/kevinkhill/lavacharts-site/blob/gh-pages/_includes/examples/combo.html) and the [Combo Docs](https://github.com/kevinkhill/lavacharts-site/blob/gh-pages/_includes/charts/combo-docs.html) is missing in the website

**Comment by kevinkhill** [comment]
Oh no! Thanks for pointing this out, I had no idea. I will add it back in.

**Comment by kevinkhill** [comment]
Fixed 👍 

http://lavacharts.com/#example-combo
